---
version: "3.8"
networks:
  media_default:
    name: media_default
    external: true
services:
  harmony-api:
    build: .
    image: mdinicola/harmony-api:latest
    container_name: harmony-api
    labels:
      # Enable routing with traefik
      - traefik.enable=true
      - traefik.http.services.hubcontrol.loadbalancer.server.port=80
      # Basic Auth
      - traefik.http.routers.hubcontrol-basic-auth.entrypoints=https
      - "traefik.http.routers.hubcontrol-basic-auth.rule=Host(`hubcontrol.mdinicola.ca`) && Query(`apikey`, `$HUBCONTROL_API_KEY`)"
      - traefik.http.routers.hubcontrol-basic-auth.service=hubcontrol
      - traefik.http.routers.hubcontrol-basic-auth.priority=100
      - traefik.http.routers.hubcontrol-basic-auth.middlewares=chain-basic-auth@file
    environment:
      - HARMONYAPIDIR=/app/config
    volumes:
      - /volume1/docker/harmony-api/config:/app/config
    ports:
      - 8000:80
    networks:
      - media_default
    restart: unless-stopped