---
# Generate API key with command: python -c "import secrets; print(secrets.token_hex(16))"
api_key: f027a50634aa163b6463ed1b82834b3c
hub_ip: 192.168.0.123

devices:
  - name: device1
    id: 12345678
    actions:
      - Action1
      - Action2
      - Action3
      - Mode
      - Oscillate
      - Speed
      - Style
      - Up Down Oscillate
  - name: device2
    id: 12345679
    actions:
      - Action1
      - Action2